name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # ou a branch que você usa para deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Authenticate to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > "${{ github.workspace }}/firebase-key.json"
          firebase login:ci --no-localhost
          firebase use --add
          firebase deploy --only hosting --token "$(firebase login:ci --no-localhost --token)"
        # OU, mais simples:
        # run: firebase deploy --only hosting --token "$(cat ${{ github.workspace }}/firebase-key.json)"
